### ISSUE TITLE
Placement of methods.js files

### ISSUE THREAD

**Issue by JackAdams** [dalequi/meteor-meteoric-boilerplate#1]
If you have your `methods.js` file in the `server` folder, you're not going to get latency compensation when calling the method from the client.

**Comment by dalequi** [comment]
You are totally right! 

As I say in the README, this boilerplate is basiclly the same structure of this app https://github.com/meteoric/meteorhunt. There, the methods.js file is only in server because there is only a method that is used to interact with the votes, and at the same time, is using helpers in the collections. So the helpers would give latency compensation, but not the method.

Anyway for a general use case I think will be better to put it shared between server and client, yes. Thanks!
